# Generated by Django 4.2.10 on 2024-03-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_author_user_alter_blogpost_author_and_more"),
        ("blog", "0012_alter_author_user"),
    ]

    operations = []
