repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: main
    hooks:
    -   id: check-unapplied-migrations
    -   id: check-absent-migrations
