name: Blog

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.9

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 manage.py test

  deploy:
    name: Deploy
    runs-on: macos-latest

    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.9

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: |
        python3 manage.py collectstatic --noinput

    - name: Migrate database
      run: |
        python3 manage.py migrate
